packages:
  - apps/*
  - packages/*
  - design-system

allowBuilds:
  better-sqlite3: true
  esbuild: true
  spawn-sync: true

dedupePeers: true

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - '@meowdown/*'
  - '@prosekit/*'
  - '@aria-ui/*'
  - prosemirror-flat-list
  - prosemirror-view
  - '@floating-ui/core@1.8.0'
  - '@floating-ui/dom@1.8.0'
  - '@floating-ui/utils@0.2.12'
  - prosemirror-model@1.25.11

# overrides:
#   '@meowdown/core': https://pkg.pr.new/prosekit/meowdown/@meowdown/core@623bc43
#   '@meowdown/react': https://pkg.pr.new/prosekit/meowdown/@meowdown/react@623bc43
# blockExoticSubdeps: false
