/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Aliases {
  alias: string;
  aliasKey: string;
  notePath: string;
}

export interface Assets {
  assetPath: string;
  notePath: string;
}

export interface Backlinks {
  alias: string | null;
  kind: string | null;
  posFrom: number | null;
  posTo: number | null;
  sourcePath: string | null;
  targetPath: string | null;
  targetRaw: string | null;
}

export interface IndexMeta {
  key: string;
  value: string;
}

export interface Links {
  alias: string | null;
  kind: string;
  posFrom: number;
  posTo: number;
  sourcePath: string;
  targetKey: string;
  targetRaw: string;
}

export interface NoteEmails {
  email: string;
  emailKey: string;
  notePath: string;
}

export interface NoteKeys {
  claimCount: string | null;
  key: string | null;
  notePath: string | null;
}

export interface Notes {
  dailyDate: string | null;
  fileHash: string;
  gistStale: Generated<number>;
  gistUrl: string | null;
  hasConflict: Generated<number>;
  id: string | null;
  isPinned: Generated<number>;
  isPrivate: Generated<number>;
  kind: Generated<string>;
  mtime: Generated<number>;
  path: string;
  pinnedOrder: number | null;
  preview: Generated<string>;
  title: string;
  titleKey: string;
  updatedAt: Generated<number>;
}

export interface NoteText {
  notePath: string;
  text: string;
}

export interface SearchFts {
  body: string | null;
  path: string | null;
  title: string | null;
}

export interface Tags {
  notePath: string;
  tag: string;
  tagKey: Generated<string>;
}

export interface Tasks {
  breadcrumbs: Generated<string>;
  checked: number;
  dueDate: string | null;
  markerOffset: number;
  notePath: string;
  raw: string;
  text: string;
}

export interface DB {
  aliases: Aliases;
  assets: Assets;
  backlinks: Backlinks;
  indexMeta: IndexMeta;
  links: Links;
  noteEmails: NoteEmails;
  noteKeys: NoteKeys;
  notes: Notes;
  noteText: NoteText;
  searchFts: SearchFts;
  tags: Tags;
  tasks: Tasks;
}
