export { setBridge, hasBridge, type IpcBridge, type Unlisten } from '../ipc/bridge'
export { call, callBinary } from '../ipc/invoke'
export {
  getAppVersion,
  getAppPlatform,
  isMobilePlatform,
  mobileStorage,
  mobileStorageLocal,
  icloudDownloadPending,
  icloudPendingCount,
  icloudStatus,
  icloudAdoptGraph,
  icloudConflictsScan,
  icloudWatchStart,
  icloudWatchStop,
  type AppPlatform,
  type IcloudDownloadScope,
  type IcloudScanOptions,
  type IcloudStatus,
  type IcloudSweepOutcome,
  type MobileStorageInfo,
  type MobileStorageKind,
} from '../ipc/commands'
export { confirmQuit, subscribeQuitRequested } from '../app/quit'
export {
  beginBackgroundTask,
  endBackgroundTask,
  type BackgroundTaskToken,
} from '../app/background-task'
export { WINDOW_NAVIGATE_EVENT, subscribeWindowNavigate } from '../app/window-events'
export { toggleDevtools } from '../app/devtools'
export {
  agentSkillStatus,
  agentSkillInstall,
  agentSkillUninstall,
  type AgentSkillInstallState,
  type AgentSkillStatus,
} from '../app/agent-skill'
export { chunkNote, type NoteChunk } from '../embeddings/chunk'
export {
  embedStatus,
  embedEnsure,
  embedTexts,
  embedApply,
  embedRemove,
  subscribeEmbedStatus,
  embedStatusSchema,
  type EmbedStatus,
  type EmbedProgress,
  type EmbedChunkPayload,
} from '../embeddings/commands'
export { embedNote, backfillEmbeddings } from '../embeddings/pipeline'
export {
  retrieve,
  relatedNotes,
  fuseRanked,
  type RetrievalHit,
  type RetrieveOptions,
} from '../embeddings/retrieve'
export {
  appErrorSchema,
  errorMessage,
  isAppError,
  toAppError,
  ReflectError,
  type AppError,
} from '../errors'
export {
  DAILY_DIR,
  NOTES_DIR,
  TEMPLATES_DIR,
  ASSETS_DIR,
  AUDIO_MEMOS_DIR,
  dailyPath,
  notePath,
  templatePath,
  assetPath,
  audioMemoPath,
  descriptionPathFor,
  DESCRIPTION_SUFFIX,
  isDaily,
  isNotePath,
  isTemplatePath,
  dateFromDailyPath,
} from '../graph/paths'
export {
  graphInfoSchema,
  recentGraphSchema,
  fileMetaSchema,
  noteCreateOutcomeSchema,
  graphImportProgressSchema,
  graphImportSummarySchema,
  windowBootstrapSchema,
  type GraphInfo,
  type RecentGraph,
  type FileMeta,
  type NoteCreateOutcome,
  type GraphImportProgress,
  type GraphImportSummary,
  type WindowBootstrap,
} from '../graph/schemas'
export {
  openGraph,
  openNoteWindow,
  windowBootstrap,
  closeNoteWindows,
  createGraph,
  importReflectV1Zip,
  subscribeImportProgress,
  cancelReflectV1Import,
  markReflectV1ImportOwnWrites,
  readNote,
  writeNote,
  createNoteIfAbsent,
  writeAsset,
  readAsset,
  openAsset,
  listDir,
  noteExists,
  deleteNote,
  listFiles,
  recentGraphs,
  forgetRecent,
  deleteGraph,
  captureHostRegister,
  captureInboxList,
  captureInboxRead,
  captureInboxSpool,
  captureInboxReject,
  captureInboxRemove,
  captureMetaFetch,
  captureSharedInboxRelay,
  promoteCaptureScreenshot,
} from '../graph/commands'
export { createAsset, importAsset } from '../graph/assets'
export { assetFileName } from '../graph/asset-names'
export {
  newNoteId,
  newNoteSource,
  untitledNoteSeed,
  untitledNotePath,
  isUntitledNotePath,
  createNoteWithTitle,
  resolveOrCreateNoteWithTitle,
  type ResolveOrCreateNoteResult,
} from '../graph/create-note'
export {
  resolveExistingWikiTarget,
  type ExistingWikiTargetResolution,
} from '../graph/resolve-existing-wiki-target'
export {
  settingsSchema,
  editorMarkdownSyntaxSchema,
  editorSpellCheckSchema,
  editorDefaultBulletSchema,
  editorBulletAfterHeadingSchema,
  editorTextSizeSchema,
  editorFullWidthSchema,
  sidebarWidthSchema,
  contextSidebarWidthSchema,
  SIDEBAR_WIDTH_RANGE,
  CONTEXT_SIDEBAR_WIDTH_RANGE,
  clampSidebarWidth,
  semanticSearchEnabledSchema,
  describeAssetsSchema,
  contactsEnabledSchema,
  themePreferenceSchema,
  timeFormatSchema,
  dateFormatSchema,
  weekStartDaySchema,
  allNotesFilterTagsSchema,
  calendarEnabledSchema,
  calendarIdsSchema,
  graphColorSchema,
  graphColorsSchema,
  GRAPH_COLOR_IDS,
  aiProviderIdSchema,
  aiProviderConfigSchema,
  aiProvidersSchema,
  defaultAiProviderIdSchema,
  chatModelSelectionSchema,
  chatSystemPromptSchema,
  CHAT_SYSTEM_PROMPT_MAX_LENGTH,
  normalizeChatSystemPrompt,
  aiPromptModeSchema,
  aiPromptSchema,
  aiPromptsSchema,
  DEFAULT_SETTINGS,
  type Settings,
  type EditorMarkdownSyntax,
  type EditorTextSize,
  type SidebarWidthRange,
  type ThemePreference,
  type TimeFormat,
  type DateFormat,
  type WeekStartDay,
  type AllNotesFilterTags,
  type CalendarIds,
  type GraphColor,
  type GraphColors,
  type AiProviderId,
  type AiProviderConfig,
  type AiPrompt,
  type AiPromptMode,
} from '../settings/schema'
export { loadSettings, saveSettings } from '../settings/commands'
export {
  contactsAuthorizationSchema,
  contactMatchSchema,
  contactsAuthorizationStatus,
  requestContactsAccess,
  lookupContactsByEmail,
  lookupContactsByName,
  isContactsReadable,
  type ContactsAuthorization,
  type ContactMatch,
} from '../contacts/commands'
export {
  contactLinkSuggestions,
  contactNamesEqual,
  matchContactForTitle,
  suggestContactForTitle,
} from '../contacts/match'
export {
  contactDetailsMarkdown,
  appendContactDetails,
  noteHasContactDetails,
} from '../contacts/markdown'
export { pickContactForEmail, resolveAttendeeContact } from '../contacts/resolve'
