//! The Rust side of the TS↔Rust parity contract (see
//! `fixtures/parity/README.md`). `expected.json` is generated by
//! `packages/core/src/indexing/parity.test.ts` from the real core pipeline;
//! this test runs the same corpus through the CLI's mirror modules and must
//! produce identical values. If it fails after a core change, update the CLI
//! mirror — never hand-edit `expected.json`.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

use dayjot_cli::hash::hash_content;
use dayjot_cli::keys::fold_key;
use dayjot_cli::note_file::{parse_note_meta, walk_notes};
use dayjot_cli::search::build_fts_match;

fn corpus_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/parity")
}

fn load_expected() -> Value {
    let raw = fs::read_to_string(corpus_dir().join("expected.json"))
        .expect("fixtures/parity/expected.json — regenerate with UPDATE_PARITY=1 (see README)");
    serde_json::from_str(&raw).unwrap()
}

fn string_array(value: &Value) -> Vec<String> {
    value
        .as_array()
        .unwrap()
        .iter()
        .map(|item| item.as_str().unwrap().to_string())
        .collect()
}

#[test]
fn corpus_and_expectations_cover_the_same_files() {
    let expected = load_expected();
    let expected_paths: BTreeSet<String> = expected["notes"]
        .as_object()
        .unwrap()
        .keys()
        .cloned()
        .collect();
    let walked: BTreeSet<String> = walk_notes(&corpus_dir())
        .unwrap()
        .into_iter()
        .map(|note| note.rel_path)
        .collect();
    assert_eq!(
        walked, expected_paths,
        "fixture files and expected.json disagree — regenerate expected.json"
    );
}

#[test]
fn note_derivations_match_the_ts_pipeline() {
    let corpus = corpus_dir();
    let expected = load_expected();
    for (rel_path, want) in expected["notes"].as_object().unwrap() {
        let content = fs::read_to_string(corpus.join(rel_path)).unwrap();
        let meta = parse_note_meta(rel_path, &content);

        assert_eq!(meta.id.as_deref(), want["id"].as_str(), "{rel_path}: id");
        assert_eq!(
            meta.title,
            want["title"].as_str().unwrap(),
            "{rel_path}: title"
        );
        assert_eq!(
            fold_key(&meta.title),
            want["titleKey"].as_str().unwrap(),
            "{rel_path}: titleKey"
        );
        assert_eq!(
            meta.aliases,
            string_array(&want["aliases"]),
            "{rel_path}: aliases"
        );
        let alias_keys: Vec<String> = meta.aliases.iter().map(|alias| fold_key(alias)).collect();
        assert_eq!(
            alias_keys,
            string_array(&want["aliasKeys"]),
            "{rel_path}: aliasKeys"
        );
        assert_eq!(
            meta.private,
            want["private"].as_bool().unwrap(),
            "{rel_path}: private"
        );
        assert_eq!(
            hash_content(&content),
            want["fileHash"].as_str().unwrap(),
            "{rel_path}: fileHash"
        );
    }
}

#[test]
fn fold_key_matches_the_ts_pipeline() {
    let expected = load_expected();
    for (input, want) in expected["foldKey"].as_object().unwrap() {
        assert_eq!(
            fold_key(input),
            want.as_str().unwrap(),
            "foldKey({input:?})"
        );
    }
}

#[test]
fn fts_match_building_matches_the_ts_pipeline() {
    let expected = load_expected();
    for (input, want) in expected["ftsMatch"].as_object().unwrap() {
        let got = build_fts_match(input);
        match want.as_str() {
            Some(expression) => assert_eq!(got.as_deref(), Some(expression), "ftsMatch({input:?})"),
            None => assert_eq!(got, None, "ftsMatch({input:?})"),
        }
    }
}
