/**
 * `@dayjot/core` sync domain (Plan 12) — GitHub backup & sync over the Rust
 * git primitives: typed command bindings, the GitHub module (device flow,
 * token refresh, repo API), and the debounced sync engine.
 */
export {
  gitStatus,
  gitSetup,
  gitDisconnect,
  gitClone,
  gitCommitAll,
  gitFetch,
  gitMergeRemote,
  gitPush,
  gitStatusSchema,
  commitOutcomeSchema,
  remoteDeltaSchema,
  mergeOutcomeSchema,
  pushOutcomeSchema,
  skippedFileSchema,
  changedFileSchema,
  type GitStatus,
  type CommitOutcome,
  type RemoteDelta,
  type MergeOutcome,
  type PushOutcome,
  type SkippedFile,
  type ChangedFile,
} from './commands'
export {
  GITHUB_APP_CLIENT_ID,
  GITHUB_APP_SLUG,
  GITHUB_AUTH_SECRET,
  githubAppInstallUrl,
  isDeviceFlowConfigured,
  githubAuthSchema,
  saveGithubAuth,
  loadGithubAuth,
  clearGithubAuth,
  deviceFlowStart,
  deviceFlowPoll,
  runDeviceFlow,
  refreshGithubAuth,
  getGithubToken,
  parseGithubRemote,
  githubRemoteUrl,
  newRepoUrl,
  BACKUP_REPO_DESCRIPTION,
  createGithubRepo,
  getGithubRepo,
  getAuthenticatedUser,
  type GithubAuth,
  type DeviceFlowStart,
  type DevicePollResult,
  type RunDeviceFlowOptions,
  type GithubRepoRef,
  type GithubRepo,
  type GithubUser,
} from './github'
export {
  createGist,
  updateGist,
  deleteGist,
  type PublishedGist,
  type GistFile,
} from './gists'
export {
  createSyncEngine,
  isSyncError,
  type SyncEngine,
  type SyncEngineOptions,
  type SyncErrorKind,
  type SyncStatus,
} from './engine'
